language: objective-c
osx_image: xcode11.6

cache:
  directories:
  - Carthage

before_script:
    - carthage bootstrap --cache-builds

script:
    - set -o pipefail && xcodebuild -project RileyLink.xcodeproj -scheme Shared build -destination 'name=iPhone 8' test | xcpretty
