language: objective-c
osx_image: xcode10
xcode_project: RileyLink.xcodeproj
xcode_scheme: RileyLink
before_script:
    - git config --global protocol.version 1
script:
    - xcodebuild -project RileyLink.xcodeproj -scheme RileyLink build -destination 'name=iPhone SE' test
